### ISSUE TITLE
[R] Refactor DataViewBoard

### ISSUE THREAD

**Issue by stefanreifenberg** [bigomics/omicsplayground#76]
- [x] DataViewBoard (l#260), a more efficient way is to use c(head(order(-rho),15), tail(order(-rho),15)). This way you don't need to reorder as it is already in the required order.
- [x] DataViewBoard (l#647), With the exception of NULL, if originally eg is of length 0, then when choosing the first element of eg will give you NA. Therefore only the null check is required.
- [x] DataViewBoard (l#1503), Rather than adding extra empty columns, it might make it look neater to change the width of the table.
